import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/navbar"
import Footer from "@/app/components/footer"
import SessionWrapper from "@/app/components/sessionwrapper"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionWrapper>
          <Navbar/>
          <div className="min-h-[87vh]">
          {/* <div class="absolute inset-0 -z-10 h-full w-full items-center px-5 py-24 [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]"></div> */}
            {children}
          </div>
          <Footer/> 
        </SessionWrapper>   
      </body>
    </html>
  );
}
